image: eu.gcr.io/***REMOVED***/ci-build-image
stages:
  - lint
  - test

# Any branch
lint:
  stage: lint
  script:
    - ./run.sh lint

test:
  stage: test
  script:
    - ./run.sh init
    - ./run.sh test
